baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "Liam Stojanovic's Site"
theme = 'PaperMod'

[params]
defaultTheme = "auto"
disableThemeToggle = true
homeInfoParams = false

[[menu.main]]
name = ""
url = ""
weight = 1

[params.profileMode]
enabled = true
title = "Hi! :)"
subtitle = "Former Fortune 100 consultant turned indie builder. Follow along as I craft software and share what I learn! More to come soon."
imageUrl = "/liam.jpeg"
imageTitle = "Liam Mihailo Stojanovic"
imageWidth = 120
imageHeight = 120
buttons = []

[[params.socialIcons]]
name = "github"
url = "https://github.com/liamstojanovic"

[[params.socialIcons]]
name = "freecodecamp"
url = "https://www.freecodecamp.org/liamstojanovic"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/channel/UC5WHMmBfaghru_t556jzk1A"

[[params.socialIcons]]
name = "email"
url = "mailto:talk_to_liam@proton.me"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/liam-stojanovic/"